version: 1

before:
  # Templates for the commands to be ran.
  hooks:
    - go generate ./...
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin


archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  sort: asc
  groups:
    - title: "Releases"
      regexp: '(release|Release)'
      order: 0
    - title: Features
      regexp: '(feature|feat|Feat|Feature)'
      order: 1
    - title: "Bug fixes"
      regexp: '(fix|bug|Fix|Bug)'
      order: 2
    - title: Others
      order: 999
  filters:
    include:
      - "(feature|feat|Feat|Feature)"
      - "(fix|bug|Fix|Bug)"
      - "(release|Release)"

announce:
  slack:
    enabled: true
    message_template: 'New Release: {{ .ProjectName }} {{.Tag}} is published! Check it out at {{ .ReleaseURL }}'
    channel: 'releases'
    username: 'Goreleaser'
    icon_emoji: ':rocket:'
    icon_url: ''
    blocks: []
    attachments: []