version: 1

before:
  # Templates for the commands to be ran.
  hooks:
    - make clean
    - go generate ./...
    - go mod tidy
    - ./generate_changelog.sh {{.Tag}} > message.txt

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Release"
      regexp: '^.*?release(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    include:
      - "^feat"
      - "^bug"
      - "^release"

announce:
  slack:
    enabled: true
    message_template: |
      iTower {{.Tag}} is out!
      
      Changelog:
      {{.Changelog}}
    channel: 'releases'
    username: 'Goreleaser'
    icon_emoji: ':rocket:'
    icon_url: ''
    blocks: []
    attachments: []
